# Generated by Django 4.0.3 on 2022-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_profile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
