# Generated by Django 4.0.3 on 2022-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_cost_customer_user_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='from_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cost',
            name='to_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
