# Generated by Django 4.0.3 on 2022-04-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_userprofile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_order',
            name='collect_by_user',
            field=models.IntegerField(),
        ),
    ]
