# Generated by Django 4.0.3 on 2022-04-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_place_order_collect_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
