# Generated by Django 4.0.3 on 2022-04-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_place_order_collect_by_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
