# Generated by Django 4.0.3 on 2022-04-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_place_order_transportation_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_order',
            name='collect_at',
        ),
        migrations.RemoveField(
            model_name='place_order',
            name='transportation_cost',
        ),
    ]
