# Generated by Django 4.0.3 on 2022-04-14 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0027_remove_place_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportcost',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.place_order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportcost',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place_order',
            name='order_status',
            field=models.CharField(default='on_transit', max_length=100),
        ),
    ]
