# Generated by Django 4.0.3 on 2022-04-14 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_place_order_user_transportcost_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
