# Generated by Django 4.0.3 on 2022-04-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_place_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transportcost',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transportcost',
            name='user',
        ),
    ]
