# Generated by Django 4.0.3 on 2022-04-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_transportcost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transportcost',
            name='user',
        ),
    ]
